name: Bootcamp 2020 CI

on:
  push:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Installing Node module
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12  
    
    - name: Installing surge
      run: npm install --global surge
      
    - name: deploying global surge
      run:  surge ./ asimilyas.surge.sh --token ${{ secrets.BOOTCAMP_SURGE_TOKEN}}  
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
